package com.caci.brickfactory.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
public class Ord{
    
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @Column(name="ORD_REFERENCE",nullable = false)
    private Long ordRef;

    @Column(name="ORD_VALUE")
    private Integer amountOfBrick;

    @Builder.Default
    @Column(name="ORD_STATUS")
    private String status = "not processed";



    public Long getOrdRef() {
        return ordRef;
    }
    
    //No Need for setter here as it is autoGenerated

    public int getAmountOfBrick() {
        return amountOfBrick;
    }
    public void setAmountOfBrick(Integer amountOfBrick) {
        this.amountOfBrick = amountOfBrick;
    }

    public String getStatus() {
        return status;
    }
    public void setStatus(String status) {
        this.status = status;
    }
    



    

}